[general]
import = ["~/.config/alacritty/colors/ashokai-urple.toml"]
live_config_reload = true

[env]
TERM = "screen-256color"

[font]
size = 12

[font.bold]
family = "FiraCode Nerd Font Mono"
#family = "Inconsolata-dz for Powerline"
style = "Bold"

[font.bold_italic]
#family = "Inconsolata-dz for Powerline"
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
#family = "Inconsolata-dz for Powerline"
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
#family = "Inconsolata-dz for Powerline"
family = "FiraCode Nerd Font Mono"

[font.offset]
x = 0
y = 2

[window]
decorations = "Transparent"
dynamic_padding = true
opacity = 0.85

[window.padding]
x = 4
y = 4
