# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

".pdf" = "ï‡"
"alacritty" = "ï„ "
"bookify" = "ï“½"
"calculator" = "ï‡¬"
"ch.proton.bridge-gui" = "ïƒ "
"chrome" = "ï‰¨"
"discord" = "ï‡—"
"disk usage" = "ï‚ ""
"file manager" = "ï¼"
"firefox" = "ï‰©"
"gimp" = "ï€¾"
"github" = "ï„“"
"google" = "ï† "
"gthumb" = "ï€¾"
"keepassxc" = "ï‚„"
"kitty" = "ï„ "
"libreoffice calc" = "ï‡ƒ"
"libreoffice impress" = "ï‡„"
"libreoffice draw" = "ï‡…"
"libreoffice writer" = "ï…œ"
"libreoffice" = "ï…›"
"menu" = "ï …"
"mpv" = "ï€½"
"music" = "ï€"
"neovide" = "îŸ…"
"nvim" = "îŸ…"
"private browsing" = "ïˆ›"
"rust" = "î¨"
"spotify" = "ï†¼"
"teams-for-linux" = "ïƒ€"
"thunar" = "ï¼"
"thunderbird" = "ïƒ "
"transmission" = "ï€™"
"videostream" = "ï€½"
"vlc" = "ï€½"
"whatsapp" = "ïˆ²"
"whatsdesk" = "ïˆ²"
fallback = "ğŸ‘»"

#[other]
#fallback_icon = "ğŸ‘»"
#deduplicate_icons = false
#separator = ": "
